/**
 * Analysis-pipeline shapes served by `assistant-service`.
 *
 * owning-service: assistant-service
 * source-of-truth: services/assistant-service/openapi.json#/components/schemas/
 *   — AnalysisTask, AnalysisPlan, PlanStep, StepParams, StepResult,
 *     AnalysisResponse, TimeRange, FilterCondition (pydantic models in
 *     services/assistant-service/app/schemas/{task,plan,response}.py),
 *     plus SSEEventName (enum at app/schemas/events.py). Projected to
 *     TypeScript by `openapi-typescript` into ./generated/assistant.d.ts.
 *
 * ════════════════════════════════════════════════════════════════════
 *  SSOT ─  backend pydantic schemas
 *  generated by ─ frontend `npm run gen:types`
 *   → ../../shared/types/generated/assistant.d.ts
 *  enforced by ─ `scripts/check-contracts.py`
 *   · assistant-openapi-snapshot-fresh        (export-openapi.py --check)
 *   · frontend-generated-types-fresh          (openapi-typescript --check)
 * ════════════════════════════════════════════════════════════════════
 *
 * This file is a thin **facade** on top of the auto-generated
 * `components['schemas'][...]` entries. Caller import paths (18+ files
 * under `frontend/src/features/`) reference this file directly; keeping
 * the path stable means a "switch to generated types" migration does
 * not ripple through every feature module.
 *
 * Rules for maintainers:
 *   1. NEVER add a field by editing this file. Change the matching
 *      pydantic model in `services/assistant-service/app/schemas/**`,
 *      re-run `python3 scripts/export-openapi.py` and
 *      `(cd frontend && npm run gen:types)`, and commit the diff.
 *   2. A type here may ONLY widen / alias / mutate-ize the generated
 *      shape (see `Mutable<>` in `./generated/mutable`). Adding extra
 *      properties that do not exist in `components['schemas']` breaks
 *      the "backend is SSOT" contract — put client-only shapes in
 *      `./common` or `./infra` instead.
 *   3. Purely client-side types (`BackendInfo`, `SemanticMetric`,
 *      `SemanticDimension`) map to anonymous dict payloads that the
 *      backend returns without a pydantic `response_model`. They are
 *      retained here as hand-written contract mirrors until their
 *      routes grow response models; until then they are guarded by
 *      `scripts/check-contracts.py::frontend-analysis-*` line checks.
 */
import type { components } from './generated/assistant';
import type { Mutable } from './generated/mutable';

type Schemas = components['schemas'];

// ════════════════════════════════════════
// Task Layer (generated: AnalysisTask, TimeRange, FilterCondition)
// ════════════════════════════════════════

export type TimeRange = Mutable<Schemas['TimeRange']>;

export type FilterCondition = Mutable<Schemas['FilterCondition']>;

export type AnalysisTask = Mutable<Schemas['AnalysisTask']>;

// ════════════════════════════════════════
// Plan Layer (generated: StepParams, StepResult, PlanStep, AnalysisPlan)
// ════════════════════════════════════════

export type StepParams = Mutable<Schemas['StepParams']>;

export type StepResult = Mutable<Schemas['StepResult']>;

/**
 * Mirror of the backend `plan.py::PlanStep.status` literal.
 * Kept as a standalone union so existing consumers
 * (`PlanTimeline/index.tsx`) can reference it without peeling it out
 * of `PlanStep['status']` at every call site.
 */
export type StepStatus = PlanStep['status'];

export type PlanStep = Mutable<Schemas['PlanStep']>;

export type AnalysisPlan = Mutable<Schemas['AnalysisPlan']>;

// ════════════════════════════════════════
// Response Layer (generated: AnalysisResponse)
// ════════════════════════════════════════

/**
 * Mirror of `response.py::AnalysisResponse.status`. Same rationale as
 * `StepStatus` above: callers need the union as a bare type.
 */
export type AnalysisStatus = AnalysisResponse['status'];

export type AnalysisResponse = Mutable<Schemas['AnalysisResponse']>;

// ════════════════════════════════════════
// SSE Event payloads
// ────────────────────────────────────────
//  The backend does NOT expose every SSE event payload as a pydantic
//  model — e.g. `status_change` data is assembled inline in
//  `analysis_service.py`. These client-side shapes mirror those inline
//  dicts and are the single place the frontend commits to that wire
//  vocabulary. When a backend commit adds or changes one of those
//  payloads, the matching field must be updated here in the same PR;
//  `scripts/check-contracts.py::sse-event-names-match-backend` enforces
//  the event-NAME side of the contract, and the shape side is covered
//  by targeted integration tests under `features/analysis/services/`.
// ════════════════════════════════════════

export type SSEEventType = Schemas['SSEEventName'];

export interface SSEStatusChangeData {
  status: string;
  session_id?: string;
  thread_id?: string;
  threadId?: string;
}

export interface SSEStepStartedData {
  step_id: string;
  description: string;
}

export interface SSEStepSqlData {
  step_id: string;
  sql: string;
}

export interface SSEStepCompletedData {
  step_id: string;
  row_count: number;
}

export interface SSEStepFailedData {
  step_id: string;
  error: string;
}

export interface SSEErrorData {
  code: string;
  message: string;
}

// ════════════════════════════════════════
// Backend / Metadata (anonymous dicts — no pydantic response_model yet)
// ════════════════════════════════════════

export interface BackendInfo {
  backend_id: string;
  backend_type: string;
  capabilities: string[];
}

/**
 * Hand-written mirror of the `TableInfo` shape returned by
 * GET /api/v1/analysis/backends/{backend_id}/schemas/{schema}/tables.
 * The backend's pydantic `TableInfo` IS registered in OpenAPI (it is
 * part of the response-body registry), but the route itself wraps it
 * in an anonymous `{tables: [...]}` envelope without a response_model;
 * until that envelope grows a schema this union stays hand-written.
 */
export interface TableInfo {
  name: string;
  schema_name: string;
  row_count?: number | null;
}

export interface ColumnInfo {
  name: string;
  data_type: string;
  is_nullable: boolean;
}

// ════════════════════════════════════════
// Semantic Layer (hand-written — /api/v1/semantic/* returns dicts)
// ════════════════════════════════════════

export interface SemanticMetric {
  id: number;
  name: string;
  display_name?: string;
  description?: string;
  calculation: string;
  source_table: string;
  source_schema: string;
  backend_id: string;
  data_type?: string;
}

export interface SemanticDimension {
  id: number;
  name: string;
  display_name?: string;
  source_column: string;
  source_table: string;
  source_schema: string;
  backend_id: string;
}

// ════════════════════════════════════════
// Request (generated: AnalysisRequest)
// ════════════════════════════════════════

/**
 * The backend pydantic model makes every budget field required with a
 * default; the frontend historically sent them as optional POST body
 * keys ("use the server defaults"). Make them optional here so the
 * existing `AnalysisRequestInput` call shape at the composer still
 * type-checks. Widening is safe: the backend accepts missing keys and
 * substitutes the pydantic defaults.
 */
export type AnalysisRequest = {
  question: Schemas['AnalysisRequest']['question'];
  threadId: Schemas['AnalysisRequest']['threadId'];
  max_steps?: Schemas['AnalysisRequest']['max_steps'];
  max_llm_calls?: Schemas['AnalysisRequest']['max_llm_calls'];
  max_wall_time_sec?: Schemas['AnalysisRequest']['max_wall_time_sec'];
  max_sql_executions?: Schemas['AnalysisRequest']['max_sql_executions'];
};

/**
 * Frontend-only union covering the full state machine the UI walks the
 * session through. The backend's `AnalysisResponse.status` literal
 * (`AnalysisStatus` above) is a strict subset (terminal states only):
 * the transient states (`understanding`, `resolving`, `planning`, ...)
 * are projected from SSE `status_change` events on the client and
 * never travel back in an `AnalysisResponse` payload. Keeping this
 * union hand-written is the correct boundary — it is a UI concern,
 * not a wire contract.
 */
export type SessionStatus =
  | 'idle'
  | 'received'
  | 'understanding'
  | 'resolving'
  | 'planning'
  | 'executing'
  | 'summarizing'
  | 'completed'
  | 'partial'
  | 'failed'
  | 'cancelled'
  | 'clarification_needed';
