/**
 * Conversation thread + session history shapes served by `assistant-service`.
 *
 * owning-service: assistant-service
 * source-of-truth: services/assistant-service/openapi.json#/components/schemas/
 *   — ConversationThreadResponse, ConversationHistoryItem,
 *     ConversationDetailResponse, CreateConversationRequest,
 *     UpdateConversationRequest (pydantic models in
 *     services/assistant-service/app/schemas/conversation.py; fields
 *     carried in camelCase via the `CamelModel` alias generator).
 *
 * ════════════════════════════════════════════════════════════════════
 *  SSOT ─  backend pydantic schemas (app/schemas/conversation.py)
 *  generated by ─ frontend `npm run gen:types`
 *   → ../../shared/types/generated/assistant.d.ts
 *  enforced by ─ `scripts/check-contracts.py`
 *   · assistant-openapi-snapshot-fresh
 *   · frontend-generated-types-fresh
 * ════════════════════════════════════════════════════════════════════
 *
 * See the companion facade header in `./analysis.d.ts` for maintainer
 * rules. Backend pydantic models here use `alias_generator=to_camel`
 * so `components['schemas']['ConversationThreadResponse']` already
 * ships camelCase keys — these facade aliases carry the name callers
 * know (`ConversationThread`, `ConversationDetail`) while the wire
 * shape itself is the generated type.
 */
import type { components } from './generated/assistant';
import type { Mutable } from './generated/mutable';
import type { AnalysisPlan, AnalysisTask, PlanStep, SessionStatus } from './analysis';

type Schemas = components['schemas'];

// ════════════════════════════════════════
// Generated-backed aliases
// ════════════════════════════════════════

/**
 * Intersect the generated shape with the subset of fields that callers
 * treat as more tightly typed than "string" on the wire:
 *   · `status` ─ backend serialises `ConversationThread.status` as a
 *     bare `str`; the UI treats it as a closed `active | archived`
 *     union. Narrow here at the facade boundary.
 *   · `task` / `plan` / `stepResults` ─ backend persists the historical
 *     session payload as JSON blobs and exposes them typed as `dict`
 *     (generated TS sees `{ [key: string]: unknown }`). The frontend
 *     has the stricter shape already (`AnalysisTask`, `AnalysisPlan`,
 *     `PlanStep[]`) so we intersect that in at the boundary.
 */
export type ConversationThread = Mutable<Schemas['ConversationThreadResponse']> & {
  status: 'active' | 'archived';
};

export type ConversationHistoryItem = Omit<
  Mutable<Schemas['ConversationHistoryItem']>,
  'status' | 'task' | 'plan' | 'stepResults'
> & {
  status: SessionStatus;
  task?: AnalysisTask | null;
  plan?: AnalysisPlan | null;
  stepResults: PlanStep[];
};

export type ConversationDetail = Mutable<Schemas['ConversationDetailResponse']> & {
  thread: ConversationThread;
  history: ConversationHistoryItem[];
};

// ════════════════════════════════════════
// Request payloads (generated: Create/UpdateConversationRequest)
// ════════════════════════════════════════

/**
 * Caller shape: every field optional on the wire except the backend-
 * selector. Deriving straight from the generated `CreateConversationRequest`
 * would surface `backendId` as the canonical name (backend uses
 * `CamelModel`) — keep the alias name local so the feature code's
 * existing usage does not churn.
 */
export type CreateConversationRequest = Mutable<Schemas['CreateConversationRequest']>;

export type UpdateConversationRequest = Mutable<Schemas['UpdateConversationRequest']>;
