/**
 * SSE stream event map + client callback / connection shape served by
 * `assistant-service`'s `POST /api/v1/analysis` endpoint.
 *
 * owning-service: assistant-service
 * source-of-truth: services/assistant-service/openapi.json#/components/schemas/SSEEventName
 *   — backend enum `app.schemas.events.SSEEventType`, surfaced as the
 *     generated `components['schemas']['SSEEventName']` string union.
 *     Per-event payload shapes (SSEStatusChangeData, ...) are imported
 *     from ./analysis, which itself derives them from the generated
 *     OpenAPI components.
 *
 * ════════════════════════════════════════════════════════════════════
 *  SSOT ─  backend pydantic enum `app.schemas.events.SSEEventType`
 *           (surfaced as `components['schemas']['SSEEventName']`)
 *  generated by ─ frontend `npm run gen:types`
 *  enforced by ─ `scripts/check-contracts.py::sse-event-names-match-backend`
 * ════════════════════════════════════════════════════════════════════
 *
 * `SSEEventMap` / `SSECallbacks` / `SSEConnection` are client-only shapes
 * and have no wire counterpart: they describe how `shared/api/sse.ts`
 * surfaces the stream to feature code. The per-event payload types they
 * reference are re-exported from `./analysis`, which in turn derives
 * them from the generated OpenAPI schemas.
 */
import type {
  AnalysisTask,
  AnalysisPlan,
  AnalysisResponse,
  SSEStatusChangeData,
  SSEStepStartedData,
  SSEStepSqlData,
  SSEStepCompletedData,
  SSEStepFailedData,
  SSEErrorData,
} from './analysis';
import type { components } from './generated/assistant';

// ════════════════════════════════════════
// SSE Event Map — maps event names to their typed payloads
// ════════════════════════════════════════

export interface SSEEventMap {
  status_change: SSEStatusChangeData;
  task_parsed: AnalysisTask;
  clarification: { question: string };
  plan_created: AnalysisPlan;
  step_started: SSEStepStartedData;
  step_sql: SSEStepSqlData;
  step_completed: SSEStepCompletedData;
  step_failed: SSEStepFailedData;
  summary_ready: { summary: string };
  analysis_done: AnalysisResponse;
  warning: { message: string };
  error: SSEErrorData;
}

/**
 * Type-level assertion: the event-name union in `SSEEventMap` must
 * cover exactly the set generated from the backend enum. If the backend
 * renames `status_change` or adds `foo_happened`, rerunning
 * `npm run gen:types` will update `components['schemas']['SSEEventName']`,
 * this assertion will fail to type-check, and the author of the backend
 * change must add the matching `SSEEventMap` entry here — the classic
 * "break typecheck in CI, not at runtime" acceptance bar of Task 4.
 */
type _AssertSSEEventMapCoversBackend = {
  readonly forward: components['schemas']['SSEEventName'] extends keyof SSEEventMap
    ? true
    : never;
  readonly reverse: keyof SSEEventMap extends components['schemas']['SSEEventName']
    ? true
    : never;
};
export type __SSEEventMapCoverage = _AssertSSEEventMapCoversBackend;

export type SSEEventName = keyof SSEEventMap;

// ════════════════════════════════════════
// SSE Callbacks — type-safe event handler
// ════════════════════════════════════════

export interface SSECallbacks {
  /**
   * Called for each SSE event. The `data` parameter is typed according to the event name.
   */
  onEvent: <K extends SSEEventName>(eventType: K, data: SSEEventMap[K]) => void;
  /** Called when a non-recoverable error occurs. */
  onError?: (error: Error) => void;
  /** Called when the SSE stream ends normally. */
  onComplete?: () => void;
  /** Called when the connection is lost (network error). */
  onDisconnect?: (error: Error) => void;
}

// ════════════════════════════════════════
// SSE Connection handle — returned by the SSE client
// ════════════════════════════════════════

export interface SSEConnection {
  /** Abort the SSE stream (user cancellation). */
  abort: () => void;
  /** Whether the connection has been aborted by the user. */
  readonly aborted: boolean;
}
