INVALID_ARGUMENT = 40000
AUTHENTICATION_REQUIRED = 40100
INVALID_CREDENTIALS = 40101
INVALID_TOKEN = 40102
INVALID_TOKEN_TYPE = 40103
ACCESS_DENIED = 40300
RESOURCE_NOT_FOUND = 40400
RESOURCE_CONFLICT = 40900
DEPENDENCY_ERROR = 50200
INTERNAL_ERROR = 50000

INVALID_ARGUMENT_NAME = "INVALID_ARGUMENT"
AUTHENTICATION_REQUIRED_NAME = "AUTHENTICATION_REQUIRED"
INVALID_CREDENTIALS_NAME = "INVALID_CREDENTIALS"
INVALID_TOKEN_NAME = "INVALID_TOKEN"
INVALID_TOKEN_TYPE_NAME = "INVALID_TOKEN_TYPE"
ACCESS_DENIED_NAME = "ACCESS_DENIED"
RESOURCE_NOT_FOUND_NAME = "RESOURCE_NOT_FOUND"
RESOURCE_CONFLICT_NAME = "RESOURCE_CONFLICT"
METHOD_NOT_ALLOWED_NAME = "METHOD_NOT_ALLOWED"
DEPENDENCY_ERROR_NAME = "DEPENDENCY_ERROR"
INTERNAL_ERROR_NAME = "INTERNAL_ERROR"


def resolve_error_code_name(code: int) -> str | None:
    return {
        400: INVALID_ARGUMENT_NAME,
        INVALID_ARGUMENT: INVALID_ARGUMENT_NAME,
        401: AUTHENTICATION_REQUIRED_NAME,
        AUTHENTICATION_REQUIRED: AUTHENTICATION_REQUIRED_NAME,
        INVALID_CREDENTIALS: INVALID_CREDENTIALS_NAME,
        INVALID_TOKEN: INVALID_TOKEN_NAME,
        INVALID_TOKEN_TYPE: INVALID_TOKEN_TYPE_NAME,
        403: ACCESS_DENIED_NAME,
        ACCESS_DENIED: ACCESS_DENIED_NAME,
        404: RESOURCE_NOT_FOUND_NAME,
        RESOURCE_NOT_FOUND: RESOURCE_NOT_FOUND_NAME,
        405: METHOD_NOT_ALLOWED_NAME,
        409: RESOURCE_CONFLICT_NAME,
        RESOURCE_CONFLICT: RESOURCE_CONFLICT_NAME,
        500: INTERNAL_ERROR_NAME,
        DEPENDENCY_ERROR: DEPENDENCY_ERROR_NAME,
        INTERNAL_ERROR: INTERNAL_ERROR_NAME,
    }.get(code)
