"""Alembic env.py for assistant-service.

Design contract (see docs/development/backend.md §12.2):

- Alembic is the SSOT for application tables in the ``pixels_analysis``
  logical database. ``Base.metadata`` is imported from the app so that
  ``alembic revision --autogenerate`` can detect model drift; however, the
  autogenerated output still requires human review before being committed.

- This env.py resolves the database URL from ``ROVER_DATABASE_URL`` (same
  env var used by the app at runtime). If the URL targets the async driver
  ``mysql+aiomysql``, we rewrite it to the sync driver ``mysql+pymysql``
  for Alembic; the sync URL is used purely by Alembic and does not leak
  into application runtime code.

- ``compare_type`` / ``compare_server_default`` are enabled so that
  autogenerate catches column type and default drift. This still misses
  index/constraint nuances in MySQL — every autogen output must be
  reviewed by a human before merge.

- Offline mode ("generate SQL without a live DB") is supported but not
  part of the standard flow; included only so that CI can emit SQL for
  DBAs to review if needed.
"""

from __future__ import annotations

import os
import sys
from logging.config import fileConfig
from pathlib import Path

from sqlalchemy import engine_from_config, pool

from alembic import context

_HERE = Path(__file__).resolve().parent
_PROJECT_ROOT = _HERE.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from app.database import Base  # noqa: E402
import app.models  # noqa: F401,E402  populate Base.metadata with every model

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _resolve_url() -> str:
    """Return a synchronous SQLAlchemy URL for Alembic.

    Precedence:
      1. ``-x db_url=...`` passed via CLI (``alembic -x db_url=... upgrade head``)
      2. ``ROVER_DATABASE_URL`` env var
      3. ``ALEMBIC_DATABASE_URL`` env var (escape hatch for CI / maintenance)

    If the resolved URL uses ``mysql+aiomysql``, rewrite it to
    ``mysql+pymysql`` so the synchronous Alembic context can connect.
    """
    cli_opts = context.get_x_argument(as_dictionary=True)
    url = (
        cli_opts.get("db_url")
        or os.getenv("ROVER_DATABASE_URL")
        or os.getenv("ALEMBIC_DATABASE_URL")
    )
    if not url:
        raise RuntimeError(
            "Alembic could not resolve a database URL. Set ROVER_DATABASE_URL "
            "(preferred; same var as the app) or ALEMBIC_DATABASE_URL, or pass "
            "-x db_url=<sync-url>. Refusing to start with a blank URL to avoid "
            "accidentally migrating the wrong database."
        )
    if url.startswith("mysql+aiomysql://"):
        url = url.replace("mysql+aiomysql://", "mysql+pymysql://", 1)
    return url


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting to a DB."""
    url = _resolve_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Apply migrations to a live database."""
    url = _resolve_url()

    cfg = config.get_section(config.config_ini_section) or {}
    cfg["sqlalchemy.url"] = url

    connectable = engine_from_config(
        cfg,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
