"""init analysis schema

Revision ID: 0001
Revises:
Create Date: 2026-04-22 00:00:00.000000

Initial migration for the assistant-service application tables under the
``pixels_analysis`` logical database.

Scope contract (see docs/development/backend.md §12.2):

- This migration owns the "zero → current ORM" DDL. Any pre-existing
  ``assistant-service`` table that used to be created by the now-removed
  ``Base.metadata.create_all()`` path is re-materialized here.
- The migration is intentionally written by hand rather than autogenerated
  to keep column ordering stable and readable. Autogenerate output was
  consulted but the file was authored to match the ORM definitions in
  ``app/models/*.py`` exactly.
- Per §12.2, once merged to main this file is IMMUTABLE. Schema evolution
  goes through new migration files (V2, V3, ...), not edits to this one.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "analysis_sessions",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("user_id", sa.Integer, nullable=False),
        sa.Column("thread_id", sa.String(length=36), nullable=False),
        sa.Column("question", sa.Text, nullable=False),
        sa.Column("backend_id", sa.String(length=128), nullable=False),
        sa.Column("schema_name", sa.String(length=128), nullable=True),
        sa.Column("model_profile", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False, server_default="received"),
        sa.Column("task_json", sa.JSON, nullable=True),
        sa.Column("plan_json", sa.JSON, nullable=True),
        sa.Column("summary", sa.Text, nullable=True),
        sa.Column("warnings", sa.JSON, nullable=True),
        sa.Column("error", sa.Text, nullable=True),
        sa.Column("envelope_json", sa.JSON, nullable=False),
        sa.Column("steps_executed", sa.Integer, nullable=False, server_default="0"),
        sa.Column("llm_calls_made", sa.Integer, nullable=False, server_default="0"),
        sa.Column("sql_executions", sa.Integer, nullable=False, server_default="0"),
        sa.Column("wall_time_ms", sa.Integer, nullable=True),
        sa.Column("created_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.Column("completed_at", sa.DateTime, nullable=True),
    )
    op.create_index(
        "ix_analysis_sessions_thread_id",
        "analysis_sessions",
        ["thread_id"],
    )

    op.create_table(
        "analysis_steps",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("step_id", sa.String(length=16), nullable=False),
        sa.Column("sequence_number", sa.Integer, nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("params_json", sa.JSON, nullable=True),
        sa.Column("sql_generated", sa.Text, nullable=True),
        sa.Column("result_json", sa.JSON, nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text, nullable=True),
        sa.Column("duration_ms", sa.Integer, nullable=True),
        sa.Column("created_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
    )
    op.create_index(
        "ix_analysis_steps_session_id",
        "analysis_steps",
        ["session_id"],
    )

    op.create_table(
        "conversation_threads",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("user_id", sa.Integer, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("backend_id", sa.String(length=128), nullable=False),
        sa.Column("schema_name", sa.String(length=128), nullable=True),
        sa.Column("model_profile", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.Column(
            "updated_at",
            sa.DateTime,
            nullable=False,
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
        ),
        sa.Column("last_activity_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
    )
    op.create_index(
        "ix_conversation_threads_user_id",
        "conversation_threads",
        ["user_id"],
    )

    op.create_table(
        "semantic_metrics",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(length=128), nullable=False, unique=True),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("calculation", sa.Text, nullable=False),
        sa.Column("source_table", sa.String(length=256), nullable=False),
        sa.Column("source_schema", sa.String(length=128), nullable=False),
        sa.Column("backend_id", sa.String(length=128), nullable=False),
        sa.Column("data_type", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
    )
    op.create_index(
        "ix_semantic_metrics_name",
        "semantic_metrics",
        ["name"],
        unique=True,
    )

    op.create_table(
        "semantic_dimensions",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(length=128), nullable=False, unique=True),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.Column("source_column", sa.String(length=256), nullable=False),
        sa.Column("source_table", sa.String(length=256), nullable=False),
        sa.Column("source_schema", sa.String(length=128), nullable=False),
        sa.Column("backend_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime, nullable=False, server_default=sa.func.now()),
    )
    op.create_index(
        "ix_semantic_dimensions_name",
        "semantic_dimensions",
        ["name"],
        unique=True,
    )

    op.create_table(
        "semantic_synonyms",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("term", sa.String(length=256), nullable=False),
        sa.Column("canonical_name", sa.String(length=256), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
    )
    op.create_index(
        "ix_semantic_synonyms_term",
        "semantic_synonyms",
        ["term"],
    )

    op.create_table(
        "semantic_join_paths",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("left_table", sa.String(length=256), nullable=False),
        sa.Column("right_table", sa.String(length=256), nullable=False),
        sa.Column("join_condition", sa.Text, nullable=False),
        sa.Column("join_type", sa.String(length=16), nullable=False, server_default="INNER"),
        sa.Column("source_schema", sa.String(length=128), nullable=False),
        sa.Column("backend_id", sa.String(length=128), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("semantic_join_paths")
    op.drop_index("ix_semantic_synonyms_term", table_name="semantic_synonyms")
    op.drop_table("semantic_synonyms")
    op.drop_index("ix_semantic_dimensions_name", table_name="semantic_dimensions")
    op.drop_table("semantic_dimensions")
    op.drop_index("ix_semantic_metrics_name", table_name="semantic_metrics")
    op.drop_table("semantic_metrics")
    op.drop_index("ix_conversation_threads_user_id", table_name="conversation_threads")
    op.drop_table("conversation_threads")
    op.drop_index("ix_analysis_steps_session_id", table_name="analysis_steps")
    op.drop_table("analysis_steps")
    op.drop_index("ix_analysis_sessions_thread_id", table_name="analysis_sessions")
    op.drop_table("analysis_sessions")
