-- Flyway V1: initial application tables for auth-service.
--
-- Scope (see docs/development/backend.md §12.2):
--   * Owns all application tables under the `pixels_auth` logical database.
--   * The logical database itself is created by db/pixels_rover.sql via MySQL
--     initdb.d (backend.md §12.1); this migration assumes it already exists.
--   * `CREATE TABLE IF NOT EXISTS` guards are kept so that if auth-service ever
--     starts against a pre-existing database that already has these tables
--     (historical initdb.d deploys), Flyway's baseline-on-migrate=true path
--     can adopt the state without conflict.
--
-- Immutability rule: once merged to main, DO NOT edit this file. Follow-up
-- changes must land as new V2__*.sql / V3__*.sql files. Flyway enforces this
-- by checksum on every startup; editing in-place triggers a migration failure
-- and fails the container.

CREATE TABLE IF NOT EXISTS `user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    `email` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    `affiliation` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    `password` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `auth_session` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `session_id` VARCHAR(36) NOT NULL,
    `user_id` BIGINT NOT NULL,
    `user_email` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    `refresh_token_hash` VARCHAR(64) NOT NULL,
    `current_refresh_token_id` VARCHAR(36) NOT NULL,
    `refresh_token_expires_at` TIMESTAMP NOT NULL,
    `last_activity_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `user_agent` VARCHAR(255) NULL,
    `client_ip` VARCHAR(64) NULL,
    `revoked_at` TIMESTAMP NULL,
    `revoked_reason` VARCHAR(128) NULL,
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uk_auth_session_session_id` (`session_id` ASC),
    INDEX `idx_auth_session_user_id` (`user_id` ASC),
    CONSTRAINT `fk_auth_session_user`
        FOREIGN KEY (`user_id`)
        REFERENCES `user` (`id`)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_bin;
